- name: Command with Changed When
  become: yes
  ansible.builtin.command: 
    cmd: apt install -y {{ pkg_name }}
  register: salida_apt
  changed_when: "'is already the newest version' not in salida_apt.stdout"
