---
- name: Blocks and tasks
  block:
   - name: Install Apache2 on Debian or Ubuntu
     become: yes
     apt:
       name:
       - apache2
       state: latest
     notify: Restar Service Web Debian_Ubuntu
     when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"


   - name: Install HTTP and memcached
     become: yes
     dnf:
       name:
       - httpd
       state: latest
     notify: Restar Service Web AlmaLinux_RockyLinux
     when: ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky"
