---
- name: Blocks tasks and error
  block:
   - name: Read the configuration of lsb_release 
     become: yes
     command: lsb_release -d
     register: version0
  rescue:
   - name: No exist command lsb_release
     command: cat /etc/issue
     register: version1
     when: ansible_distribution == "Debian"

   - name: No exist command lsb_release
     command: cat /etc/issue
     register: version2
     when: ansible_distribution == "Ubuntu"

   - name: No exist command lsb_release
     command: cat /etc/redhat-release
     register: version3
     when: ansible_distribution == "AlmaLinux"

   - name: No exist command lsb_release
     command: cat /etc/redhat-release
     register: version4
     when: ansible_distribution == "Rocky"

  always:
   - name: See the version
     debug:
       msg: 
        - "{{ version0.stdout }}"
        - "{{ version1.stdout }}"
        - "{{ version2.stdout }}"
        - "{{ version3.stdout }}"
        - "{{ version4.stdout }}"
