---
- name: Blocks tasks and error
  block:
   - name: Read the configuration of lsb_release 
     become: yes
     command: lsb_release -a
     register: version
  rescue:
   - name: No exist command lsb_release
     command: cat /etc/*release | egrep "^NAME|^VERSION=" | cut -d = -f2
     register: version
     when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
   - name: No exist command lsb_release
     command: cat /etc/*release | egrep "^NAME|^VERSION=" | cut -d = -f2
     register: version
     when: ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky"
  always:
   - name: See the version
     debug:
       msg: "{{ version.stdout }}"
