- name: Command with Ignore_errors
  ansible.builtin.command: 
    cmd: cat {{ archivo }}
  register: salida_cat
  ignore_errors: true

- debug:
    msg: "Contenido del archivo: {{ salida_cat.stdout_lines }}"
  when: salida_cat is succeeded

- debug:
    msg: "Error comando: {{ salida_cat.stderr }}"
  when: salida_cat is failed
