- name: Command with Ignore_errors
  ansible.builtin.command: 
    cmd: cat {{ archivo }}
  register: salida_cat
  ignore_errors: true

- debug:
    msg: "Contenido del archivo: {{ salida_cat.stdout }}"
  when: not salida_cat|failed

- debug:
    msg: "Error comando: {{ salida_cat.stderr }}"
  when: salida_cat|failed
