---
- name:  Restar Service Web Linux Based on Debian
  become: true
  service: 
    name: apache2
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name:  Restar Service Web Linux Based on Red Hat
  become: true
  service: 
    name: httpd
    state: restarted
  when: ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky"
