- name: Blocks and tasks
  block:
    name: Install httpd and memcached
    ansible.builtin.yum:
      name:
      - httpd
      - memcached
      state: present

    name: Start service bar and aneble
    ansible.builtin.service:
      name: bar
      state: started
      anebled: true
    when: ansible_facts['distribution'] == AlmaLinux or ansible_facts['distribution'] == Rocky
    become: true
    ignore_error: true