---
- name: Blocks and tasks
  block:
   - name: Install httpd and memcached
     become: yes
     ansible.builtin.dnf:
       name:
       - httpd
       - memcached
       state: present

   - name: The service httpd start and aneble
     become: yes
     systemd:
       name: httpd
       state: stopped
       anebled: true
     when: ansible_facts['distribution'] == "AlmaLinux" or ansible_facts['distribution'] == "Rocky"
     ignore_errors: true

   - name: The service memcached start and aneble
     become: yes
     systemd:
       name: memcached
       state: stopped
       anebled: true
     when: ansible_facts['distribution'] == "AlmaLinux" or ansible_facts['distribution'] == "Rocky"
     ignore_errors: true
