---
- name: Blocks and tasks
  block:
   - name: Install httpd and memcached
     become: yes
     ansible.builtin.dnf:
       name:
       - httpd
       - memcached
       state: present

   - name: The service bar start and aneble
     become: yes
     ansible.builtin.service:
       name: bar
       state: started
       anebled: true
     when: ansible_facts['distribution'] == "AlmaLinux" or ansible_facts['distribution'] == "Rocky"
     ignore_error: true
